#!/bin/sh


if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" ]; then
    dpkg-divert --package sagitta-xdm-conf --remove --rename --divert /etc/X11/xdm/Xsetup.distrib /etc/X11/xdm/Xsetup
    dpkg-divert --package sagitta-xdm-conf --remove --rename --divert /etc/X11/xdm/Xresources.distrib /etc/X11/xdm/Xresources
fi
