#!/bin/sh

dpkg-divert --add --rename --divert /etc/init.d/xdm.orig /etc/init.d/xdm
dpkg-divert --add --rename --divert /etc/X11/xdm/Xsetup.orig /etc/X11/xdm/Xsetup
dpkg-divert --add --rename --divert /etc/X11/xdm/Xresources.orig /etc/X11/xdm/Xresources
